liip_imagine :
#    resolvers :
#        default :
#            web_path :
#                web_root:

    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../public"

    filter_sets:
        cache: ~

        # the name of the "filter set"
        projects_list:

            # adjust the image quality to 75%
            quality: 100

            # list of transformations to apply (the "filters")
            filters:
                relative_resize:
                    widen: 600